// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(AzurePricingContext))]
    partial class AzurePricingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"), 1L, 1);

                    b.Property<string>("armRegionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("armSkuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("effectiveStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isPrimaryMeterRegion")
                        .HasColumnType("bit");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("meterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reservationTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("retailPrice")
                        .HasColumnType("real");

                    b.Property<string>("serviceFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skuId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("skuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("tierMinimumUnits")
                        .HasColumnType("real");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("unitPrice")
                        .HasColumnType("real");

                    b.HasKey("ItemId");

                    b.ToTable("PricingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
